// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: todos/v1/todos.proto

package todosv1

import (
	metadata "github.com/aldok10/zara-rpc/metadata"
	routing "github.com/aldok10/zara-rpc/routing"
	runtime "github.com/aldok10/zara-rpc/runtime"
	status "github.com/aldok10/zara-rpc/status"
	grpc "google.golang.org/grpc"
	metadata1 "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// gatewayTodoService adapts the grpc-go client to the zararpc HTTP handler
// contract. It is used by RegisterTodoServiceGateway.
type gatewayTodoService struct {
	UnimplementedTodoServiceHandler
	client TodoServiceClient
}

func (g *gatewayTodoService) CreateTodo(ctx runtime.Ctx, req *CreateTodoRequest) (*Todo, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.CreateTodo(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayTodoService) ListTodos(ctx runtime.Ctx, req *ListTodosRequest) (*ListTodosResponse, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.ListTodos(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayTodoService) GetTodo(ctx runtime.Ctx, req *GetTodoRequest) (*Todo, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.GetTodo(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayTodoService) UpdateTodo(ctx runtime.Ctx, req *UpdateTodoRequest) (*Todo, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.UpdateTodo(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayTodoService) DeleteTodo(ctx runtime.Ctx, req *DeleteTodoRequest) (*emptypb.Empty, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.DeleteTodo(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

// RegisterTodoServiceGateway registers REST routes on mux that proxy
// every call to the gRPC server reachable through conn.
func RegisterTodoServiceGateway(mux *routing.Mux, conn *grpc.ClientConn) error {
	svc := &gatewayTodoService{client: NewTodoServiceClient(conn)}
	return RegisterTodoServiceRoutes(mux, svc)
}
