// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: todos/v1/todos.proto

package todosv1

import (
	context "context"
	client "github.com/aldok10/zara-rpc/client"
	codes "github.com/aldok10/zara-rpc/codes"
	encoding "github.com/aldok10/zara-rpc/encoding"
	kernel "github.com/aldok10/zara-rpc/kernel"
	peer "github.com/aldok10/zara-rpc/peer"
	routing "github.com/aldok10/zara-rpc/routing"
	runtime "github.com/aldok10/zara-rpc/runtime"
	status "github.com/aldok10/zara-rpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
)

// TodoServiceHandler is the server implementation contract.
type TodoServiceHandler interface {
	CreateTodo(runtime.Ctx, *CreateTodoRequest) (*Todo, error)
	ListTodos(runtime.Ctx, *ListTodosRequest) (*ListTodosResponse, error)
	GetTodo(runtime.Ctx, *GetTodoRequest) (*Todo, error)
	UpdateTodo(runtime.Ctx, *UpdateTodoRequest) (*Todo, error)
	DeleteTodo(runtime.Ctx, *DeleteTodoRequest) (*emptypb.Empty, error)
}

// UnimplementedTodoServiceHandler returns CodeUnimplemented for every method.
type UnimplementedTodoServiceHandler struct{}

func (UnimplementedTodoServiceHandler) CreateTodo(runtime.Ctx, *CreateTodoRequest) (*Todo, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method CreateTodo not implemented")
}

func (UnimplementedTodoServiceHandler) ListTodos(runtime.Ctx, *ListTodosRequest) (*ListTodosResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method ListTodos not implemented")
}

func (UnimplementedTodoServiceHandler) GetTodo(runtime.Ctx, *GetTodoRequest) (*Todo, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method GetTodo not implemented")
}

func (UnimplementedTodoServiceHandler) UpdateTodo(runtime.Ctx, *UpdateTodoRequest) (*Todo, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method UpdateTodo not implemented")
}

func (UnimplementedTodoServiceHandler) DeleteTodo(runtime.Ctx, *DeleteTodoRequest) (*emptypb.Empty, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method DeleteTodo not implemented")
}

func request_TodoService_CreateTodo_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &CreateTodoRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_TodoService_ListTodos_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &ListTodosRequest{}
	meta := ctx.Meta()

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_TodoService_GetTodo_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &GetTodoRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_TodoService_UpdateTodo_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &UpdateTodoRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_TodoService_DeleteTodo_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &DeleteTodoRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

// Service and endpoint constants.
const (
	TodoService_FullName          = "acme.todos.v1.TodoService"
	TodoService_CreateTodo_Method = "CreateTodo"
	TodoService_CreateTodo_Path   = "/v1/todos"
	TodoService_ListTodos_Method  = "ListTodos"
	TodoService_ListTodos_Path    = "/v1/todos"
	TodoService_GetTodo_Method    = "GetTodo"
	TodoService_GetTodo_Path      = "/v1/todos/{id}"
	TodoService_UpdateTodo_Method = "UpdateTodo"
	TodoService_UpdateTodo_Path   = "/v1/todos/{id}"
	TodoService_DeleteTodo_Method = "DeleteTodo"
	TodoService_DeleteTodo_Path   = "/v1/todos/{id}"
)

// Register_CreateTodo builds the CreateTodo endpoint.
func Register_CreateTodo(svc TodoServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[CreateTodoRequest, Todo])(&op).
		SetMethod(http.MethodPost).
		SetPath(TodoService_CreateTodo_Path).
		SetRPC(TodoService_CreateTodo_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[CreateTodoRequest]) (*runtime.Response[Todo], error) {
			resp, err := svc.CreateTodo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_TodoService_CreateTodo_0).
		Build()
}

// Register_ListTodos builds the ListTodos endpoint.
func Register_ListTodos(svc TodoServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[ListTodosRequest, ListTodosResponse])(&op).
		SetMethod(http.MethodGet).
		SetPath(TodoService_ListTodos_Path).
		SetRPC(TodoService_ListTodos_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[ListTodosRequest]) (*runtime.Response[ListTodosResponse], error) {
			resp, err := svc.ListTodos(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_TodoService_ListTodos_0).
		Build()
}

// Register_GetTodo builds the GetTodo endpoint.
func Register_GetTodo(svc TodoServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[GetTodoRequest, Todo])(&op).
		SetMethod(http.MethodGet).
		SetPath(TodoService_GetTodo_Path).
		SetRPC(TodoService_GetTodo_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[GetTodoRequest]) (*runtime.Response[Todo], error) {
			resp, err := svc.GetTodo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_TodoService_GetTodo_0).
		Build()
}

// Register_UpdateTodo builds the UpdateTodo endpoint.
func Register_UpdateTodo(svc TodoServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[UpdateTodoRequest, Todo])(&op).
		SetMethod(http.MethodPut).
		SetPath(TodoService_UpdateTodo_Path).
		SetRPC(TodoService_UpdateTodo_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[UpdateTodoRequest]) (*runtime.Response[Todo], error) {
			resp, err := svc.UpdateTodo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_TodoService_UpdateTodo_0).
		Build()
}

// Register_DeleteTodo builds the DeleteTodo endpoint.
func Register_DeleteTodo(svc TodoServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[DeleteTodoRequest, emptypb.Empty])(&op).
		SetMethod(http.MethodDelete).
		SetPath(TodoService_DeleteTodo_Path).
		SetRPC(TodoService_DeleteTodo_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[DeleteTodoRequest]) (*runtime.Response[emptypb.Empty], error) {
			resp, err := svc.DeleteTodo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_TodoService_DeleteTodo_0).
		Build()
}

// RegisterTodoServiceRoutes registers all HTTP endpoints of the service on the mux.
func RegisterTodoServiceRoutes(mux *routing.Mux, svc TodoServiceHandler) error {
	return mux.Register(
		kernel.NewService(
			TodoService_FullName,
			Register_CreateTodo(svc),
			Register_ListTodos(svc),
			Register_GetTodo(svc),
			Register_UpdateTodo(svc),
			Register_DeleteTodo(svc),
		))
}

// RegisterTodoServiceHandler registers the service on target (routing.Server, routing.Mux, or gRPC registrar).
func RegisterTodoServiceHandler(target any, svc TodoServiceHandler) error {
	if reg, ok := target.(interface {
		Mux() *routing.Mux
		GRPC() any
	}); ok {
		if err := RegisterTodoServiceRoutes(reg.Mux(), svc); err != nil {
			return err
		}
		if g := reg.GRPC(); g != nil {
			RegisterTodoServiceServer(g, svc)
		}
		return nil
	}
	if mux, ok := target.(*routing.Mux); ok {
		return RegisterTodoServiceRoutes(mux, svc)
	}
	RegisterTodoServiceServer(target, svc)
	return nil
}

// TodoServiceHTTPClient is a typed HTTP client for TodoService.
type TodoServiceHTTPClient interface {
	CreateTodo(context.Context, *CreateTodoRequest, ...client.ClientOption) (*Todo, error)
	ListTodos(context.Context, *ListTodosRequest, ...client.ClientOption) (*ListTodosResponse, error)
	GetTodo(context.Context, *GetTodoRequest, ...client.ClientOption) (*Todo, error)
	UpdateTodo(context.Context, *UpdateTodoRequest, ...client.ClientOption) (*Todo, error)
	DeleteTodo(context.Context, *DeleteTodoRequest, ...client.ClientOption) (*emptypb.Empty, error)

	// Close releases any resources held by the client.
	Close() error
}

type todoServiceHTTPClient struct {
	client.ClientBase
}

// NewTodoServiceHTTPClient creates a new TodoServiceHTTPClient that calls the given base URL.
func NewTodoServiceHTTPClient(baseURL string, opts ...client.ClientOption) TodoServiceHTTPClient {
	return &todoServiceHTTPClient{ClientBase: client.NewClientBase(baseURL, opts...)}
}

func (c *todoServiceHTTPClient) CreateTodo(ctx context.Context, req *CreateTodoRequest, extraOpts ...client.ClientOption) (*Todo, error) {
	resp := &Todo{}
	err := c.DoUnary(ctx, http.MethodPost, TodoService_CreateTodo_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *todoServiceHTTPClient) ListTodos(ctx context.Context, req *ListTodosRequest, extraOpts ...client.ClientOption) (*ListTodosResponse, error) {
	resp := &ListTodosResponse{}
	err := c.DoUnary(ctx, http.MethodGet, TodoService_ListTodos_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *todoServiceHTTPClient) GetTodo(ctx context.Context, req *GetTodoRequest, extraOpts ...client.ClientOption) (*Todo, error) {
	resp := &Todo{}
	err := c.DoUnary(ctx, http.MethodGet, TodoService_GetTodo_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *todoServiceHTTPClient) UpdateTodo(ctx context.Context, req *UpdateTodoRequest, extraOpts ...client.ClientOption) (*Todo, error) {
	resp := &Todo{}
	err := c.DoUnary(ctx, http.MethodPut, TodoService_UpdateTodo_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *todoServiceHTTPClient) DeleteTodo(ctx context.Context, req *DeleteTodoRequest, extraOpts ...client.ClientOption) (*emptypb.Empty, error) {
	resp := &emptypb.Empty{}
	err := c.DoUnary(ctx, http.MethodDelete, TodoService_DeleteTodo_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *todoServiceHTTPClient) Close() error {
	return nil
}
