// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: todos/v1/todos.proto

package todosv1

import (
	context "context"
	grpcbridge "github.com/aldok10/zara-rpc/grpcbridge"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// FullMethodName constants for the service.
const (
	TodoService_CreateTodo_FullMethodName = "/acme.todos.v1.TodoService/CreateTodo"
	TodoService_ListTodos_FullMethodName  = "/acme.todos.v1.TodoService/ListTodos"
	TodoService_GetTodo_FullMethodName    = "/acme.todos.v1.TodoService/GetTodo"
	TodoService_UpdateTodo_FullMethodName = "/acme.todos.v1.TodoService/UpdateTodo"
	TodoService_DeleteTodo_FullMethodName = "/acme.todos.v1.TodoService/DeleteTodo"
)

// TodoServiceClient is the client API for TodoService.
type TodoServiceClient interface {
	CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error)
	GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*Todo, error)
	DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type todoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTodoServiceClient(cc grpc.ClientConnInterface) TodoServiceClient {
	return &todoServiceClient{cc}
}

func (c *todoServiceClient) CreateTodo(ctx context.Context, in *CreateTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_CreateTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) ListTodos(ctx context.Context, in *ListTodosRequest, opts ...grpc.CallOption) (*ListTodosResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTodosResponse)
	err := c.cc.Invoke(ctx, TodoService_ListTodos_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) GetTodo(ctx context.Context, in *GetTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_GetTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) UpdateTodo(ctx context.Context, in *UpdateTodoRequest, opts ...grpc.CallOption) (*Todo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Todo)
	err := c.cc.Invoke(ctx, TodoService_UpdateTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *todoServiceClient) DeleteTodo(ctx context.Context, in *DeleteTodoRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, TodoService_DeleteTodo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TodoService_ServiceDesc is the grpc.ServiceDesc for TodoService.
var TodoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.todos.v1.TodoService",
	HandlerType: (*TodoServiceHandler)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "CreateTodo", Handler: _TodoService_CreateTodo_Handler},
		{MethodName: "ListTodos", Handler: _TodoService_ListTodos_Handler},
		{MethodName: "GetTodo", Handler: _TodoService_GetTodo_Handler},
		{MethodName: "UpdateTodo", Handler: _TodoService_UpdateTodo_Handler},
		{MethodName: "DeleteTodo", Handler: _TodoService_DeleteTodo_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "todos/v1/todos.proto",
}

func _TodoService_CreateTodo_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CreateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(TodoServiceHandler).CreateTodo(grpcbridge.CtxFor(ctx, TodoService_CreateTodo_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: TodoService_CreateTodo_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(TodoServiceHandler).CreateTodo(grpcbridge.CtxFor(ctx, TodoService_CreateTodo_FullMethodName), req.(*CreateTodoRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_ListTodos_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ListTodosRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(TodoServiceHandler).ListTodos(grpcbridge.CtxFor(ctx, TodoService_ListTodos_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: TodoService_ListTodos_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(TodoServiceHandler).ListTodos(grpcbridge.CtxFor(ctx, TodoService_ListTodos_FullMethodName), req.(*ListTodosRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_GetTodo_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(TodoServiceHandler).GetTodo(grpcbridge.CtxFor(ctx, TodoService_GetTodo_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: TodoService_GetTodo_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(TodoServiceHandler).GetTodo(grpcbridge.CtxFor(ctx, TodoService_GetTodo_FullMethodName), req.(*GetTodoRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_UpdateTodo_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(UpdateTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(TodoServiceHandler).UpdateTodo(grpcbridge.CtxFor(ctx, TodoService_UpdateTodo_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: TodoService_UpdateTodo_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(TodoServiceHandler).UpdateTodo(grpcbridge.CtxFor(ctx, TodoService_UpdateTodo_FullMethodName), req.(*UpdateTodoRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _TodoService_DeleteTodo_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteTodoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(TodoServiceHandler).DeleteTodo(grpcbridge.CtxFor(ctx, TodoService_DeleteTodo_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: TodoService_DeleteTodo_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(TodoServiceHandler).DeleteTodo(grpcbridge.CtxFor(ctx, TodoService_DeleteTodo_FullMethodName), req.(*DeleteTodoRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterTodoServiceServer registers the service on a grpc.ServiceRegistrar or any target implementing RegisterService.
// Handlers receive runtime.Ctx (the same contract as the HTTP routes),
// so one implementation serves both transports.
func RegisterTodoServiceServer(s any, svc TodoServiceHandler) {
	if reg, ok := s.(grpc.ServiceRegistrar); ok {
		reg.RegisterService(&TodoService_ServiceDesc, svc)
	}
}
