// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: todos/v1/todos.proto

package todosv1

import (
	_ "github.com/aldok10/zara-rpc-examples/proto/zara/customtag"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateTodoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The title is the only client-supplied field; owner_id comes from the
	// authenticated claims, never from the request body.
	Title         string `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTodoRequest) Reset() {
	*x = CreateTodoRequest{}
	mi := &file_todos_v1_todos_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTodoRequest) ProtoMessage() {}

func (x *CreateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTodoRequest.ProtoReflect.Descriptor instead.
func (*CreateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{0}
}

func (x *CreateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type ListTodosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosRequest) Reset() {
	*x = ListTodosRequest{}
	mi := &file_todos_v1_todos_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosRequest) ProtoMessage() {}

func (x *ListTodosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosRequest.ProtoReflect.Descriptor instead.
func (*ListTodosRequest) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{1}
}

type ListTodosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Todos         []*Todo                `protobuf:"bytes,1,rep,name=todos,proto3" json:"todos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTodosResponse) Reset() {
	*x = ListTodosResponse{}
	mi := &file_todos_v1_todos_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTodosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTodosResponse) ProtoMessage() {}

func (x *ListTodosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTodosResponse.ProtoReflect.Descriptor instead.
func (*ListTodosResponse) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{2}
}

func (x *ListTodosResponse) GetTodos() []*Todo {
	if x != nil {
		return x.Todos
	}
	return nil
}

type GetTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTodoRequest) Reset() {
	*x = GetTodoRequest{}
	mi := &file_todos_v1_todos_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTodoRequest) ProtoMessage() {}

func (x *GetTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTodoRequest.ProtoReflect.Descriptor instead.
func (*GetTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{3}
}

func (x *GetTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Done          bool                   `protobuf:"varint,3,opt,name=done,proto3" json:"done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTodoRequest) Reset() {
	*x = UpdateTodoRequest{}
	mi := &file_todos_v1_todos_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTodoRequest) ProtoMessage() {}

func (x *UpdateTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTodoRequest.ProtoReflect.Descriptor instead.
func (*UpdateTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateTodoRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateTodoRequest) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

type DeleteTodoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTodoRequest) Reset() {
	*x = DeleteTodoRequest{}
	mi := &file_todos_v1_todos_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTodoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTodoRequest) ProtoMessage() {}

func (x *DeleteTodoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTodoRequest.ProtoReflect.Descriptor instead.
func (*DeleteTodoRequest) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteTodoRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Todo is the GORM model: every field carries (zara.options.tags) so the
// generated struct is a valid database model (primary key, index, auto
// timestamps) and maps with mapstructure. Timestamps are int64 unix
// seconds so GORM's autoCreateTime/autoUpdateTime fill them natively.
type Todo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty" gorm:"primaryKey;size:36" mapstructure:"id"`
	OwnerId       string                 `protobuf:"bytes,2,opt,name=owner_id,json=ownerId,proto3" json:"owner_id,omitempty" gorm:"index;size:36" mapstructure:"owner_id"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty" gorm:"size:255;not null" mapstructure:"title"`
	Done          bool                   `protobuf:"varint,4,opt,name=done,proto3" json:"done,omitempty" gorm:"default:false" mapstructure:"done"`
	CreatedAt     int64                  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty" gorm:"autoCreateTime" mapstructure:"created_at"`
	UpdatedAt     int64                  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty" gorm:"autoUpdateTime" mapstructure:"updated_at"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Todo) Reset() {
	*x = Todo{}
	mi := &file_todos_v1_todos_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todos_v1_todos_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todos_v1_todos_proto_rawDescGZIP(), []int{6}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetOwnerId() string {
	if x != nil {
		return x.OwnerId
	}
	return ""
}

func (x *Todo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Todo) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Todo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Todo) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

var File_todos_v1_todos_proto protoreflect.FileDescriptor

const file_todos_v1_todos_proto_rawDesc = "" +
	"\n" +
	"\x14todos/v1/todos.proto\x12\racme.todos.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1czara/customtag/options.proto\")\n" +
	"\x11CreateTodoRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\"\x12\n" +
	"\x10ListTodosRequest\">\n" +
	"\x11ListTodosResponse\x12)\n" +
	"\x05todos\x18\x01 \x03(\v2\x13.acme.todos.v1.TodoR\x05todos\" \n" +
	"\x0eGetTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x11UpdateTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04done\x18\x03 \x01(\bR\x04done\"#\n" +
	"\x11DeleteTodoRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xc7\x03\n" +
	"\x04Todo\x12?\n" +
	"\x02id\x18\x01 \x01(\tB/\x8a\xb5\x18+gorm:\"primaryKey;size:36\" mapstructure:\"id\"R\x02id\x12K\n" +
	"\bowner_id\x18\x02 \x01(\tB0\x8a\xb5\x18,gorm:\"index;size:36\" mapstructure:\"owner_id\"R\aownerId\x12G\n" +
	"\x05title\x18\x03 \x01(\tB1\x8a\xb5\x18-gorm:\"size:255;not null\" mapstructure:\"title\"R\x05title\x12@\n" +
	"\x04done\x18\x04 \x01(\bB,\x8a\xb5\x18(gorm:\"default:false\" mapstructure:\"done\"R\x04done\x12R\n" +
	"\n" +
	"created_at\x18\x05 \x01(\x03B3\x8a\xb5\x18/gorm:\"autoCreateTime\" mapstructure:\"created_at\"R\tcreatedAt\x12R\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\x03B3\x8a\xb5\x18/gorm:\"autoUpdateTime\" mapstructure:\"updated_at\"R\tupdatedAt2\xe2\x03\n" +
	"\vTodoService\x12Y\n" +
	"\n" +
	"CreateTodo\x12 .acme.todos.v1.CreateTodoRequest\x1a\x13.acme.todos.v1.Todo\"\x14\x82\xd3\xe4\x93\x02\x0e:\x01*\"\t/v1/todos\x12a\n" +
	"\tListTodos\x12\x1f.acme.todos.v1.ListTodosRequest\x1a .acme.todos.v1.ListTodosResponse\"\x11\x82\xd3\xe4\x93\x02\v\x12\t/v1/todos\x12U\n" +
	"\aGetTodo\x12\x1d.acme.todos.v1.GetTodoRequest\x1a\x13.acme.todos.v1.Todo\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/v1/todos/{id}\x12^\n" +
	"\n" +
	"UpdateTodo\x12 .acme.todos.v1.UpdateTodoRequest\x1a\x13.acme.todos.v1.Todo\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\x1a\x0e/v1/todos/{id}\x12^\n" +
	"\n" +
	"DeleteTodo\x12 .acme.todos.v1.DeleteTodoRequest\x1a\x16.google.protobuf.Empty\"\x16\x82\xd3\xe4\x93\x02\x10*\x0e/v1/todos/{id}B=Z;github.com/aldok10/zara-rpc-examples/proto/todos/v1;todosv1b\x06proto3"

var (
	file_todos_v1_todos_proto_rawDescOnce sync.Once
	file_todos_v1_todos_proto_rawDescData []byte
)

func file_todos_v1_todos_proto_rawDescGZIP() []byte {
	file_todos_v1_todos_proto_rawDescOnce.Do(func() {
		file_todos_v1_todos_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_todos_v1_todos_proto_rawDesc), len(file_todos_v1_todos_proto_rawDesc)))
	})
	return file_todos_v1_todos_proto_rawDescData
}

var file_todos_v1_todos_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_todos_v1_todos_proto_goTypes = []any{
	(*CreateTodoRequest)(nil), // 0: acme.todos.v1.CreateTodoRequest
	(*ListTodosRequest)(nil),  // 1: acme.todos.v1.ListTodosRequest
	(*ListTodosResponse)(nil), // 2: acme.todos.v1.ListTodosResponse
	(*GetTodoRequest)(nil),    // 3: acme.todos.v1.GetTodoRequest
	(*UpdateTodoRequest)(nil), // 4: acme.todos.v1.UpdateTodoRequest
	(*DeleteTodoRequest)(nil), // 5: acme.todos.v1.DeleteTodoRequest
	(*Todo)(nil),              // 6: acme.todos.v1.Todo
	(*emptypb.Empty)(nil),     // 7: google.protobuf.Empty
}
var file_todos_v1_todos_proto_depIdxs = []int32{
	6, // 0: acme.todos.v1.ListTodosResponse.todos:type_name -> acme.todos.v1.Todo
	0, // 1: acme.todos.v1.TodoService.CreateTodo:input_type -> acme.todos.v1.CreateTodoRequest
	1, // 2: acme.todos.v1.TodoService.ListTodos:input_type -> acme.todos.v1.ListTodosRequest
	3, // 3: acme.todos.v1.TodoService.GetTodo:input_type -> acme.todos.v1.GetTodoRequest
	4, // 4: acme.todos.v1.TodoService.UpdateTodo:input_type -> acme.todos.v1.UpdateTodoRequest
	5, // 5: acme.todos.v1.TodoService.DeleteTodo:input_type -> acme.todos.v1.DeleteTodoRequest
	6, // 6: acme.todos.v1.TodoService.CreateTodo:output_type -> acme.todos.v1.Todo
	2, // 7: acme.todos.v1.TodoService.ListTodos:output_type -> acme.todos.v1.ListTodosResponse
	6, // 8: acme.todos.v1.TodoService.GetTodo:output_type -> acme.todos.v1.Todo
	6, // 9: acme.todos.v1.TodoService.UpdateTodo:output_type -> acme.todos.v1.Todo
	7, // 10: acme.todos.v1.TodoService.DeleteTodo:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_todos_v1_todos_proto_init() }
func file_todos_v1_todos_proto_init() {
	if File_todos_v1_todos_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_todos_v1_todos_proto_rawDesc), len(file_todos_v1_todos_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todos_v1_todos_proto_goTypes,
		DependencyIndexes: file_todos_v1_todos_proto_depIdxs,
		MessageInfos:      file_todos_v1_todos_proto_msgTypes,
	}.Build()
	File_todos_v1_todos_proto = out.File
	file_todos_v1_todos_proto_goTypes = nil
	file_todos_v1_todos_proto_depIdxs = nil
}
