// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: zara/options.proto

package zara

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_zara_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50001,
		Name:          "zara.options.custom_tag_key",
		Tag:           "bytes,50001,rep,name=custom_tag_key",
		Filename:      "zara/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         50002,
		Name:          "zara.options.custom_tag_value",
		Tag:           "bytes,50002,rep,name=custom_tag_value",
		Filename:      "zara/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// The struct tag key, e.g. "xml", "gorm", "mapstructure".
	//
	// repeated string custom_tag_key = 50001;
	E_CustomTagKey = &file_zara_options_proto_extTypes[0]
	// The struct tag value, e.g. "flag,attr", "primaryKey". Paired with
	// custom_tag_key by index.
	//
	// repeated string custom_tag_value = 50002;
	E_CustomTagValue = &file_zara_options_proto_extTypes[1]
)

var File_zara_options_proto protoreflect.FileDescriptor

const file_zara_options_proto_rawDesc = "" +
	"\n" +
	"\x12zara/options.proto\x12\fzara.options\x1a google/protobuf/descriptor.proto:E\n" +
	"\x0ecustom_tag_key\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x03(\tR\fcustomTagKey:I\n" +
	"\x10custom_tag_value\x12\x1d.google.protobuf.FieldOptions\x18҆\x03 \x03(\tR\x0ecustomTagValueB6Z4github.com/aldok10/zara-rpc-examples/proto/zara;zarab\x06proto3"

var file_zara_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_zara_options_proto_depIdxs = []int32{
	0, // 0: zara.options.custom_tag_key:extendee -> google.protobuf.FieldOptions
	0, // 1: zara.options.custom_tag_value:extendee -> google.protobuf.FieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zara_options_proto_init() }
func file_zara_options_proto_init() {
	if File_zara_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zara_options_proto_rawDesc), len(file_zara_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_zara_options_proto_goTypes,
		DependencyIndexes: file_zara_options_proto_depIdxs,
		ExtensionInfos:    file_zara_options_proto_extTypes,
	}.Build()
	File_zara_options_proto = out.File
	file_zara_options_proto_goTypes = nil
	file_zara_options_proto_depIdxs = nil
}
