// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: zara/customtag/options.proto

package customtag

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_zara_customtag_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50001,
		Name:          "zara.options.tags",
		Tag:           "bytes,50001,opt,name=tags",
		Filename:      "zara/customtag/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.OneofOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         50002,
		Name:          "zara.options.oneof_tags",
		Tag:           "bytes,50002,opt,name=oneof_tags",
		Filename:      "zara/customtag/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// The full struct tag literal for the field, e.g.
	// `xml:"flag,attr" gorm:"primaryKey"`.
	//
	// optional string tags = 50001;
	E_Tags = &file_zara_customtag_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.OneofOptions.
var (
	// The full struct tag literal for the oneof field.
	//
	// optional string oneof_tags = 50002;
	E_OneofTags = &file_zara_customtag_options_proto_extTypes[1]
)

var File_zara_customtag_options_proto protoreflect.FileDescriptor

const file_zara_customtag_options_proto_rawDesc = "" +
	"\n" +
	"\x1czara/customtag/options.proto\x12\fzara.options\x1a google/protobuf/descriptor.proto:3\n" +
	"\x04tags\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\tR\x04tags:>\n" +
	"\n" +
	"oneof_tags\x12\x1d.google.protobuf.OneofOptions\x18҆\x03 \x01(\tR\toneofTagsBEZCgithub.com/aldok10/zara-rpc-examples/proto/zara/customtag;customtagb\x06proto3"

var file_zara_customtag_options_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
	(*descriptorpb.OneofOptions)(nil), // 1: google.protobuf.OneofOptions
}
var file_zara_customtag_options_proto_depIdxs = []int32{
	0, // 0: zara.options.tags:extendee -> google.protobuf.FieldOptions
	1, // 1: zara.options.oneof_tags:extendee -> google.protobuf.OneofOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_zara_customtag_options_proto_init() }
func file_zara_customtag_options_proto_init() {
	if File_zara_customtag_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_zara_customtag_options_proto_rawDesc), len(file_zara_customtag_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_zara_customtag_options_proto_goTypes,
		DependencyIndexes: file_zara_customtag_options_proto_depIdxs,
		ExtensionInfos:    file_zara_customtag_options_proto_extTypes,
	}.Build()
	File_zara_customtag_options_proto = out.File
	file_zara_customtag_options_proto_goTypes = nil
	file_zara_customtag_options_proto_depIdxs = nil
}
