// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: users/v1/users.proto

package usersv1

import (
	context "context"
	client "github.com/aldok10/zara-rpc/client"
	codes "github.com/aldok10/zara-rpc/codes"
	encoding "github.com/aldok10/zara-rpc/encoding"
	metadata "github.com/aldok10/zara-rpc/metadata"
	peer "github.com/aldok10/zara-rpc/peer"
	runtime "github.com/aldok10/zara-rpc/runtime"
	status "github.com/aldok10/zara-rpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	reflect "reflect"
)

// UsersServiceHandler is the server implementation contract.
type UsersServiceHandler interface {
	GetUser(context.Context, *GetUserRequest) (*User, error)
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error)
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	WatchUsers(context.Context, *WatchUsersRequest, runtime.ServerStream[*User]) error
	UploadUsers(context.Context, runtime.ClientStream[*User]) (*UploadUsersResponse, error)
	Chat(context.Context, runtime.BidiStream[*ChatMessage, *ChatMessage]) error
}

// UnimplementedUsersServiceHandler returns CodeUnimplemented for every method.
type UnimplementedUsersServiceHandler struct{}

func (UnimplementedUsersServiceHandler) GetUser(context.Context, *GetUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method GetUser not implemented")
}

func (UnimplementedUsersServiceHandler) ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method ListUsers not implemented")
}

func (UnimplementedUsersServiceHandler) CreateUser(context.Context, *CreateUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method CreateUser not implemented")
}

func (UnimplementedUsersServiceHandler) UpdateUser(context.Context, *UpdateUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method UpdateUser not implemented")
}

func (UnimplementedUsersServiceHandler) DeleteUser(context.Context, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method DeleteUser not implemented")
}

func (UnimplementedUsersServiceHandler) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method Echo not implemented")
}

func (UnimplementedUsersServiceHandler) WatchUsers(context.Context, *WatchUsersRequest, runtime.ServerStream[*User]) error {
	return status.NewErrorf(codes.CodeUnimplemented, "method WatchUsers not implemented")
}

func (UnimplementedUsersServiceHandler) UploadUsers(context.Context, runtime.ClientStream[*User]) (*UploadUsersResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method UploadUsers not implemented")
}

func (UnimplementedUsersServiceHandler) Chat(context.Context, runtime.BidiStream[*ChatMessage, *ChatMessage]) error {
	return status.NewErrorf(codes.CodeUnimplemented, "method Chat not implemented")
}

func request_UsersService_GetUser_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &GetUserRequest{}

	var err error

	// Path parameters.
	if v, ok := params["id"]; ok {
		var tmp string
		tmp, err = runtime.PathString(v)
		if err != nil {
			return nil, status.NewErrorf(codes.CodeInvalidArgument, "type mismatch, parameter: id, error: %v", err)
		}
		msg.Id = tmp
	}

	// Query parameters (reuse the query parsed by the mux).
	if err := runtime.PopulateQuery(msg, metadata.RequestMetaFromContext(ctx).Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_ListUsers_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &ListUsersRequest{}

	// Query parameters (reuse the query parsed by the mux).
	if err := runtime.PopulateQuery(msg, metadata.RequestMetaFromContext(ctx).Query); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_CreateUser_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &CreateUserRequest{}

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(metadata.RequestMetaFromContext(ctx).Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_UpdateUser_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &UpdateUserRequest{}

	var err error

	// Path parameters.
	if v, ok := params["id"]; ok {
		var tmp string
		tmp, err = runtime.PathString(v)
		if err != nil {
			return nil, status.NewErrorf(codes.CodeInvalidArgument, "type mismatch, parameter: id, error: %v", err)
		}
		msg.Id = tmp
	}

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(metadata.RequestMetaFromContext(ctx).Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_DeleteUser_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &DeleteUserRequest{}

	var err error

	// Path parameters.
	if v, ok := params["id"]; ok {
		var tmp string
		tmp, err = runtime.PathString(v)
		if err != nil {
			return nil, status.NewErrorf(codes.CodeInvalidArgument, "type mismatch, parameter: id, error: %v", err)
		}
		msg.Id = tmp
	}

	// Query parameters (reuse the query parsed by the mux).
	if err := runtime.PopulateQuery(msg, metadata.RequestMetaFromContext(ctx).Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_Echo_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &EchoRequest{}

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(metadata.RequestMetaFromContext(ctx).Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_Echo_1(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &EchoRequest{}

	var err error

	// Path parameters.
	if v, ok := params["message"]; ok {
		var tmp string
		tmp, err = runtime.PathString(v)
		if err != nil {
			return nil, status.NewErrorf(codes.CodeInvalidArgument, "type mismatch, parameter: message, error: %v", err)
		}
		msg.Message = tmp
	}

	// Query parameters (reuse the query parsed by the mux).
	if err := runtime.PopulateQuery(msg, metadata.RequestMetaFromContext(ctx).Query, "message"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_WatchUsers_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &WatchUsersRequest{}

	// Query parameters (reuse the query parsed by the mux).
	if err := runtime.PopulateQuery(msg, metadata.RequestMetaFromContext(ctx).Query); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_UploadUsers_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &User{}

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(metadata.RequestMetaFromContext(ctx).Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_Chat_0(ctx context.Context, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &ChatMessage{}

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(metadata.RequestMetaFromContext(ctx).Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, metadata.RequestMetaFromContext(ctx).Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

// Service and endpoint constants.
const (
	UsersService_FullName           = "acme.users.v1.UsersService"
	UsersService_GetUser_Method     = "GetUser"
	UsersService_GetUser_Path       = "/v1/users/{id}"
	UsersService_ListUsers_Method   = "ListUsers"
	UsersService_ListUsers_Path     = "/v1/users"
	UsersService_CreateUser_Method  = "CreateUser"
	UsersService_CreateUser_Path    = "/v1/users"
	UsersService_UpdateUser_Method  = "UpdateUser"
	UsersService_UpdateUser_Path    = "/v1/users/{id}"
	UsersService_DeleteUser_Method  = "DeleteUser"
	UsersService_DeleteUser_Path    = "/v1/users/{id}"
	UsersService_Echo_Method        = "Echo"
	UsersService_Echo_Path          = "/v1/echo"
	UsersService_Echo_Path_1        = "/v1/echo/{message}"
	UsersService_WatchUsers_Method  = "WatchUsers"
	UsersService_WatchUsers_Path    = "/v1/users:watch"
	UsersService_UploadUsers_Method = "UploadUsers"
	UsersService_UploadUsers_Path   = "/v1/users:upload"
	UsersService_Chat_Method        = "Chat"
	UsersService_Chat_Path          = "/v1/chat"
)

// Register_GetUser builds the GetUser endpoint.
func Register_GetUser(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodGet,
		UsersService_GetUser_Path,
		func(ctx context.Context, req *runtime.Request[GetUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.GetUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_GetUser_Method),
		runtime.WithRequestBuilder(request_UsersService_GetUser_0),
	)
}

// Register_ListUsers builds the ListUsers endpoint.
func Register_ListUsers(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodGet,
		UsersService_ListUsers_Path,
		func(ctx context.Context, req *runtime.Request[ListUsersRequest]) (*runtime.Response[ListUsersResponse], error) {
			resp, err := svc.ListUsers(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_ListUsers_Method),
		runtime.WithRequestBuilder(request_UsersService_ListUsers_0),
	)
}

// Register_CreateUser builds the CreateUser endpoint.
func Register_CreateUser(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodPost,
		UsersService_CreateUser_Path,
		func(ctx context.Context, req *runtime.Request[CreateUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.CreateUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_CreateUser_Method),
		runtime.WithBody("*"),
		runtime.WithRequestBuilder(request_UsersService_CreateUser_0),
	)
}

// Register_UpdateUser builds the UpdateUser endpoint.
func Register_UpdateUser(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodPut,
		UsersService_UpdateUser_Path,
		func(ctx context.Context, req *runtime.Request[UpdateUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.UpdateUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_UpdateUser_Method),
		runtime.WithBody("*"),
		runtime.WithRequestBuilder(request_UsersService_UpdateUser_0),
	)
}

// Register_DeleteUser builds the DeleteUser endpoint.
func Register_DeleteUser(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodDelete,
		UsersService_DeleteUser_Path,
		func(ctx context.Context, req *runtime.Request[DeleteUserRequest]) (*runtime.Response[emptypb.Empty], error) {
			resp, err := svc.DeleteUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_DeleteUser_Method),
		runtime.WithRequestBuilder(request_UsersService_DeleteUser_0),
	)
}

// Register_Echo builds the Echo endpoint.
func Register_Echo(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodPost,
		UsersService_Echo_Path,
		func(ctx context.Context, req *runtime.Request[EchoRequest]) (*runtime.Response[EchoResponse], error) {
			resp, err := svc.Echo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_Echo_Method),
		runtime.WithBody("*"),
		runtime.WithRequestBuilder(request_UsersService_Echo_0),
	)
}

// Register_Echo_1 builds the Echo endpoint.
func Register_Echo_1(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewEndpoint(
		http.MethodGet,
		UsersService_Echo_Path_1,
		func(ctx context.Context, req *runtime.Request[EchoRequest]) (*runtime.Response[EchoResponse], error) {
			resp, err := svc.Echo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_Echo_Method),
		runtime.WithRequestBuilder(request_UsersService_Echo_1),
	)
}

// Register_WatchUsers builds the WatchUsers endpoint.
func Register_WatchUsers(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewServerStreamEndpoint(
		http.MethodGet,
		UsersService_WatchUsers_Path,
		func(ctx context.Context, req *runtime.Request[WatchUsersRequest], stream runtime.ServerStream[*User]) error {
			return svc.WatchUsers(ctx, req.Msg(), stream)
		},
		runtime.WithRPC(UsersService_WatchUsers_Method),
		runtime.WithStreamType(runtime.StreamTypeServer),
		runtime.WithRequestBuilder(request_UsersService_WatchUsers_0),
	)
}

// Register_UploadUsers builds the UploadUsers endpoint.
func Register_UploadUsers(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewClientStreamEndpoint(
		http.MethodPost,
		UsersService_UploadUsers_Path,
		func(ctx context.Context, stream runtime.ClientStream[*User]) (*runtime.Response[UploadUsersResponse], error) {
			resp, err := svc.UploadUsers(ctx, stream)
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		},
		runtime.WithRPC(UsersService_UploadUsers_Method),
		runtime.WithStreamType(runtime.StreamTypeClient),
	)
}

// Register_Chat builds the Chat endpoint.
func Register_Chat(svc UsersServiceHandler) *runtime.Endpoint {
	return runtime.NewBidiStreamEndpoint(
		http.MethodPost,
		UsersService_Chat_Path,
		func(ctx context.Context, stream runtime.BidiStream[*ChatMessage, *ChatMessage]) error {
			return svc.Chat(ctx, stream)
		},
		runtime.WithRPC(UsersService_Chat_Method),
		runtime.WithStreamType(runtime.StreamTypeBidi),
		runtime.WithBody("*"),
	)
}

// RegisterUsersServiceRoutes registers all HTTP endpoints of the service on the mux.
func RegisterUsersServiceRoutes(mux *runtime.Mux, svc UsersServiceHandler) error {
	return mux.Register(runtime.NewService(UsersService_FullName).
		Add(Register_GetUser(svc)).
		Add(Register_ListUsers(svc)).
		Add(Register_CreateUser(svc)).
		Add(Register_UpdateUser(svc)).
		Add(Register_DeleteUser(svc)).
		Add(Register_Echo(svc)).
		Add(Register_Echo_1(svc)).
		Add(Register_WatchUsers(svc)).
		Add(Register_UploadUsers(svc)).
		Add(Register_Chat(svc)))
}

// UsersServiceHTTPClient is a typed HTTP client for UsersService.
type UsersServiceHTTPClient interface {
	GetUser(context.Context, *GetUserRequest, ...client.ClientOption) (*User, error)
	ListUsers(context.Context, *ListUsersRequest, ...client.ClientOption) (*ListUsersResponse, error)
	CreateUser(context.Context, *CreateUserRequest, ...client.ClientOption) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest, ...client.ClientOption) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest, ...client.ClientOption) (*emptypb.Empty, error)
	Echo(context.Context, *EchoRequest, ...client.ClientOption) (*EchoResponse, error)
	WatchUsers(context.Context, *WatchUsersRequest, ...client.ClientOption) (client.ServerStreamForClient[User], error)
	UploadUsers(context.Context, ...client.ClientOption) (client.ClientStreamForClient[User, UploadUsersResponse], error)
	Chat(context.Context, ...client.ClientOption) (client.BidiStreamForClient[ChatMessage, ChatMessage], error)

	// Close releases any resources held by the client.
	Close() error
}

type usersServiceHTTPClient struct {
	client.ClientBase
}

// NewUsersServiceHTTPClient creates a new UsersServiceHTTPClient that calls the given base URL.
func NewUsersServiceHTTPClient(baseURL string, opts ...client.ClientOption) UsersServiceHTTPClient {
	return &usersServiceHTTPClient{ClientBase: client.NewClientBase(baseURL, opts...)}
}

func (c *usersServiceHTTPClient) GetUser(ctx context.Context, req *GetUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodGet, UsersService_GetUser_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) ListUsers(ctx context.Context, req *ListUsersRequest, extraOpts ...client.ClientOption) (*ListUsersResponse, error) {
	resp := &ListUsersResponse{}
	err := c.DoUnary(ctx, http.MethodGet, UsersService_ListUsers_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) CreateUser(ctx context.Context, req *CreateUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodPost, UsersService_CreateUser_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) UpdateUser(ctx context.Context, req *UpdateUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodPut, UsersService_UpdateUser_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) DeleteUser(ctx context.Context, req *DeleteUserRequest, extraOpts ...client.ClientOption) (*emptypb.Empty, error) {
	resp := &emptypb.Empty{}
	err := c.DoUnary(ctx, http.MethodDelete, UsersService_DeleteUser_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) Echo(ctx context.Context, req *EchoRequest, extraOpts ...client.ClientOption) (*EchoResponse, error) {
	resp := &EchoResponse{}
	err := c.DoUnary(ctx, http.MethodPost, UsersService_Echo_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) WatchUsers(ctx context.Context, req *WatchUsersRequest, extraOpts ...client.ClientOption) (client.ServerStreamForClient[User], error) {
	raw, err := c.DoServerStream(ctx, http.MethodGet, UsersService_WatchUsers_Path, req, reflect.TypeOf((*User)(nil)).Elem(), extraOpts...)
	if err != nil {
		return client.ServerStreamForClient[User]{}, err
	}
	return client.ServerStreamForClient[User]{Inner: raw}, nil
}

func (c *usersServiceHTTPClient) UploadUsers(ctx context.Context, extraOpts ...client.ClientOption) (client.ClientStreamForClient[User, UploadUsersResponse], error) {
	raw, err := c.DoClientStream(ctx, http.MethodPost, UsersService_UploadUsers_Path, reflect.TypeOf((*UploadUsersResponse)(nil)).Elem(), extraOpts...)
	if err != nil {
		return client.ClientStreamForClient[User, UploadUsersResponse]{}, err
	}
	return client.ClientStreamForClient[User, UploadUsersResponse]{Inner: raw}, nil
}

func (c *usersServiceHTTPClient) Chat(ctx context.Context, extraOpts ...client.ClientOption) (client.BidiStreamForClient[ChatMessage, ChatMessage], error) {
	raw, err := c.DoBidiStream(ctx, UsersService_Chat_Path, reflect.TypeOf((*ChatMessage)(nil)).Elem(), extraOpts...)
	if err != nil {
		return client.BidiStreamForClient[ChatMessage, ChatMessage]{}, err
	}
	return client.BidiStreamForClient[ChatMessage, ChatMessage]{Inner: raw}, nil
}

func (c *usersServiceHTTPClient) Close() error {
	return nil
}
