// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: users/v1/users.proto

package usersv1

import (
	context "context"
	client "github.com/aldok10/zara-rpc/client"
	codes "github.com/aldok10/zara-rpc/codes"
	encoding "github.com/aldok10/zara-rpc/encoding"
	kernel "github.com/aldok10/zara-rpc/kernel"
	peer "github.com/aldok10/zara-rpc/peer"
	routing "github.com/aldok10/zara-rpc/routing"
	runtime "github.com/aldok10/zara-rpc/runtime"
	status "github.com/aldok10/zara-rpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	reflect "reflect"
)

// UsersServiceHandler is the server implementation contract.
type UsersServiceHandler interface {
	GetUser(runtime.Ctx, *GetUserRequest) (*User, error)
	ListUsers(runtime.Ctx, *ListUsersRequest) (*ListUsersResponse, error)
	GetUserByID(runtime.Ctx, *GetUserRequest) (*User, error)
	CreateUser(runtime.Ctx, *CreateUserRequest) (*User, error)
	UpdateUser(runtime.Ctx, *UpdateUserRequest) (*User, error)
	DeleteUser(runtime.Ctx, *DeleteUserRequest) (*emptypb.Empty, error)
	Echo(runtime.Ctx, *EchoRequest) (*EchoResponse, error)
	GetUserProfile(runtime.Ctx, *GetUserRequest) (*User, error)
	ActivateUser(runtime.Ctx, *ActivateUserRequest) (*User, error)
	WatchUsers(runtime.Ctx, *WatchUsersRequest, runtime.ServerStream[*User]) error
	UploadUsers(runtime.Ctx, runtime.ClientStream[*User]) (*UploadUsersResponse, error)
	Chat(runtime.Ctx, runtime.BidiStream[*ChatMessage, *ChatMessage]) error
}

// UnimplementedUsersServiceHandler returns CodeUnimplemented for every method.
type UnimplementedUsersServiceHandler struct{}

func (UnimplementedUsersServiceHandler) GetUser(runtime.Ctx, *GetUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method GetUser not implemented")
}

func (UnimplementedUsersServiceHandler) ListUsers(runtime.Ctx, *ListUsersRequest) (*ListUsersResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method ListUsers not implemented")
}

func (UnimplementedUsersServiceHandler) GetUserByID(runtime.Ctx, *GetUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method GetUserByID not implemented")
}

func (UnimplementedUsersServiceHandler) CreateUser(runtime.Ctx, *CreateUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method CreateUser not implemented")
}

func (UnimplementedUsersServiceHandler) UpdateUser(runtime.Ctx, *UpdateUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method UpdateUser not implemented")
}

func (UnimplementedUsersServiceHandler) DeleteUser(runtime.Ctx, *DeleteUserRequest) (*emptypb.Empty, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method DeleteUser not implemented")
}

func (UnimplementedUsersServiceHandler) Echo(runtime.Ctx, *EchoRequest) (*EchoResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method Echo not implemented")
}

func (UnimplementedUsersServiceHandler) GetUserProfile(runtime.Ctx, *GetUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method GetUserProfile not implemented")
}

func (UnimplementedUsersServiceHandler) ActivateUser(runtime.Ctx, *ActivateUserRequest) (*User, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method ActivateUser not implemented")
}

func (UnimplementedUsersServiceHandler) WatchUsers(runtime.Ctx, *WatchUsersRequest, runtime.ServerStream[*User]) error {
	return status.NewErrorf(codes.CodeUnimplemented, "method WatchUsers not implemented")
}

func (UnimplementedUsersServiceHandler) UploadUsers(runtime.Ctx, runtime.ClientStream[*User]) (*UploadUsersResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method UploadUsers not implemented")
}

func (UnimplementedUsersServiceHandler) Chat(runtime.Ctx, runtime.BidiStream[*ChatMessage, *ChatMessage]) error {
	return status.NewErrorf(codes.CodeUnimplemented, "method Chat not implemented")
}

func request_UsersService_GetUser_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &GetUserRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_ListUsers_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &ListUsersRequest{}
	meta := ctx.Meta()

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_GetUserByID_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &GetUserRequest{}
	meta := ctx.Meta()

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_CreateUser_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &CreateUserRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_UpdateUser_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &UpdateUserRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_DeleteUser_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &DeleteUserRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_Echo_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &EchoRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_Echo_1(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &EchoRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["message"]; ok {
		msg.Message = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "message"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_GetUserProfile_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &GetUserRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["id"]; ok {
		msg.Id = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "id"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_ActivateUser_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &ActivateUserRequest{}
	meta := ctx.Meta()

	// Path parameters.
	if v, ok := params["name"]; ok {
		msg.Name = v
	}

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query, "name"); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_WatchUsers_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &WatchUsersRequest{}
	meta := ctx.Meta()

	// Query parameters (fields not bound by path or body).
	if err := runtime.PopulateQuery(msg, meta.Query); err != nil {
		return nil, err
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_UploadUsers_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &User{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_UsersService_Chat_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &ChatMessage{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

// Service and endpoint constants.
const (
	UsersService_FullName              = "acme.users.v1.UsersService"
	UsersService_GetUser_Method        = "GetUser"
	UsersService_GetUser_Path          = "/v1/users/{id}"
	UsersService_ListUsers_Method      = "ListUsers"
	UsersService_ListUsers_Path        = "/v1/users"
	UsersService_GetUserByID_Method    = "GetUserByID"
	UsersService_GetUserByID_Path      = "/v1/users/getByID"
	UsersService_CreateUser_Method     = "CreateUser"
	UsersService_CreateUser_Path       = "/v1/users"
	UsersService_UpdateUser_Method     = "UpdateUser"
	UsersService_UpdateUser_Path       = "/v1/users/{id}"
	UsersService_DeleteUser_Method     = "DeleteUser"
	UsersService_DeleteUser_Path       = "/v1/users/{id}"
	UsersService_Echo_Method           = "Echo"
	UsersService_Echo_Path             = "/v1/echo"
	UsersService_Echo_Path_1           = "/v1/echo/{message}"
	UsersService_GetUserProfile_Method = "GetUserProfile"
	UsersService_GetUserProfile_Path   = "/v1/users/{id}/profile"
	UsersService_ActivateUser_Method   = "ActivateUser"
	UsersService_ActivateUser_Path     = "/v1/users/{name}:activate"
	UsersService_WatchUsers_Method     = "WatchUsers"
	UsersService_WatchUsers_Path       = "/v1/users:watch"
	UsersService_UploadUsers_Method    = "UploadUsers"
	UsersService_UploadUsers_Path      = "/v1/users:upload"
	UsersService_Chat_Method           = "Chat"
	UsersService_Chat_Path             = "/v1/chat"
)

// Register_GetUser builds the GetUser endpoint.
func Register_GetUser(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[GetUserRequest, User])(&op).
		SetMethod(http.MethodGet).
		SetPath(UsersService_GetUser_Path).
		SetRPC(UsersService_GetUser_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[GetUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.GetUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_UsersService_GetUser_0).
		Build()
}

// Register_ListUsers builds the ListUsers endpoint.
func Register_ListUsers(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[ListUsersRequest, ListUsersResponse])(&op).
		SetMethod(http.MethodGet).
		SetPath(UsersService_ListUsers_Path).
		SetRPC(UsersService_ListUsers_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[ListUsersRequest]) (*runtime.Response[ListUsersResponse], error) {
			resp, err := svc.ListUsers(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_UsersService_ListUsers_0).
		Build()
}

// Register_GetUserByID builds the GetUserByID endpoint.
func Register_GetUserByID(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[GetUserRequest, User])(&op).
		SetMethod(http.MethodGet).
		SetPath(UsersService_GetUserByID_Path).
		SetRPC(UsersService_GetUserByID_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[GetUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.GetUserByID(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_UsersService_GetUserByID_0).
		Build()
}

// Register_CreateUser builds the CreateUser endpoint.
func Register_CreateUser(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[CreateUserRequest, User])(&op).
		SetMethod(http.MethodPost).
		SetPath(UsersService_CreateUser_Path).
		SetRPC(UsersService_CreateUser_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[CreateUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.CreateUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_UsersService_CreateUser_0).
		Build()
}

// Register_UpdateUser builds the UpdateUser endpoint.
func Register_UpdateUser(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[UpdateUserRequest, User])(&op).
		SetMethod(http.MethodPut).
		SetPath(UsersService_UpdateUser_Path).
		SetRPC(UsersService_UpdateUser_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[UpdateUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.UpdateUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_UsersService_UpdateUser_0).
		Build()
}

// Register_DeleteUser builds the DeleteUser endpoint.
func Register_DeleteUser(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[DeleteUserRequest, emptypb.Empty])(&op).
		SetMethod(http.MethodDelete).
		SetPath(UsersService_DeleteUser_Path).
		SetRPC(UsersService_DeleteUser_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[DeleteUserRequest]) (*runtime.Response[emptypb.Empty], error) {
			resp, err := svc.DeleteUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_UsersService_DeleteUser_0).
		Build()
}

// Register_Echo builds the Echo endpoint.
func Register_Echo(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[EchoRequest, EchoResponse])(&op).
		SetMethod(http.MethodPost).
		SetPath(UsersService_Echo_Path).
		SetRPC(UsersService_Echo_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[EchoRequest]) (*runtime.Response[EchoResponse], error) {
			resp, err := svc.Echo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_UsersService_Echo_0).
		Build()
}

// Register_Echo_1 builds the Echo endpoint.
func Register_Echo_1(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[EchoRequest, EchoResponse])(&op).
		SetMethod(http.MethodGet).
		SetPath(UsersService_Echo_Path_1).
		SetRPC(UsersService_Echo_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[EchoRequest]) (*runtime.Response[EchoResponse], error) {
			resp, err := svc.Echo(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_UsersService_Echo_1).
		Build()
}

// Register_GetUserProfile builds the GetUserProfile endpoint.
func Register_GetUserProfile(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[GetUserRequest, User])(&op).
		SetMethod(http.MethodGet).
		SetPath(UsersService_GetUserProfile_Path).
		SetRPC(UsersService_GetUserProfile_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[GetUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.GetUserProfile(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetResponseBody("name").
		SetRequestBuilder(request_UsersService_GetUserProfile_0).
		Build()
}

// Register_ActivateUser builds the ActivateUser endpoint.
func Register_ActivateUser(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[ActivateUserRequest, User])(&op).
		SetMethod(http.MethodPost).
		SetPath(UsersService_ActivateUser_Path).
		SetRPC(UsersService_ActivateUser_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[ActivateUserRequest]) (*runtime.Response[User], error) {
			resp, err := svc.ActivateUser(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetRequestBuilder(request_UsersService_ActivateUser_0).
		Build()
}

// Register_WatchUsers builds the WatchUsers endpoint.
func Register_WatchUsers(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[WatchUsersRequest, *User])(&op).
		SetMethod(http.MethodGet).
		SetPath(UsersService_WatchUsers_Path).
		SetRPC(UsersService_WatchUsers_Method).
		SetServerStreamHandler(func(ctx runtime.Ctx, req *runtime.Request[WatchUsersRequest], stream runtime.ServerStream[*User]) error {
			return svc.WatchUsers(ctx, req.Msg(), stream)
		}).
		SetRequestBuilder(request_UsersService_WatchUsers_0).
		Build()
}

// Register_UploadUsers builds the UploadUsers endpoint.
func Register_UploadUsers(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[*User, UploadUsersResponse])(&op).
		SetMethod(http.MethodPost).
		SetPath(UsersService_UploadUsers_Path).
		SetRPC(UsersService_UploadUsers_Method).
		SetClientStreamHandler(func(ctx runtime.Ctx, stream runtime.ClientStream[*User]) (*runtime.Response[UploadUsersResponse], error) {
			resp, err := svc.UploadUsers(ctx, stream)
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		Build()
}

// Register_Chat builds the Chat endpoint.
func Register_Chat(svc UsersServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[*ChatMessage, *ChatMessage])(&op).
		SetMethod(http.MethodPost).
		SetPath(UsersService_Chat_Path).
		SetRPC(UsersService_Chat_Method).
		SetBidiStreamHandler(func(ctx runtime.Ctx, stream runtime.BidiStream[*ChatMessage, *ChatMessage]) error {
			return svc.Chat(ctx, stream)
		}).
		SetBody("*").
		Build()
}

// RegisterUsersServiceRoutes registers all HTTP endpoints of the service on the mux.
func RegisterUsersServiceRoutes(mux *routing.Mux, svc UsersServiceHandler) error {
	return mux.Register(
		kernel.NewService(
			UsersService_FullName,
			Register_GetUser(svc),
			Register_ListUsers(svc),
			Register_GetUserByID(svc),
			Register_CreateUser(svc),
			Register_UpdateUser(svc),
			Register_DeleteUser(svc),
			Register_Echo(svc),
			Register_Echo_1(svc),
			Register_GetUserProfile(svc),
			Register_ActivateUser(svc),
			Register_WatchUsers(svc),
			Register_UploadUsers(svc),
			Register_Chat(svc),
		))
}

// RegisterUsersServiceHandler registers the service on target (routing.Server, routing.Mux, or gRPC registrar).
func RegisterUsersServiceHandler(target any, svc UsersServiceHandler) error {
	if reg, ok := target.(interface {
		Mux() *routing.Mux
		GRPC() any
	}); ok {
		if err := RegisterUsersServiceRoutes(reg.Mux(), svc); err != nil {
			return err
		}
		if g := reg.GRPC(); g != nil {
			RegisterUsersServiceServer(g, svc)
		}
		return nil
	}
	if mux, ok := target.(*routing.Mux); ok {
		return RegisterUsersServiceRoutes(mux, svc)
	}
	RegisterUsersServiceServer(target, svc)
	return nil
}

// UsersServiceHTTPClient is a typed HTTP client for UsersService.
type UsersServiceHTTPClient interface {
	GetUser(context.Context, *GetUserRequest, ...client.ClientOption) (*User, error)
	ListUsers(context.Context, *ListUsersRequest, ...client.ClientOption) (*ListUsersResponse, error)
	GetUserByID(context.Context, *GetUserRequest, ...client.ClientOption) (*User, error)
	CreateUser(context.Context, *CreateUserRequest, ...client.ClientOption) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest, ...client.ClientOption) (*User, error)
	DeleteUser(context.Context, *DeleteUserRequest, ...client.ClientOption) (*emptypb.Empty, error)
	Echo(context.Context, *EchoRequest, ...client.ClientOption) (*EchoResponse, error)
	GetUserProfile(context.Context, *GetUserRequest, ...client.ClientOption) (*User, error)
	ActivateUser(context.Context, *ActivateUserRequest, ...client.ClientOption) (*User, error)
	WatchUsers(context.Context, *WatchUsersRequest, ...client.ClientOption) (client.ServerStreamForClient[User], error)
	UploadUsers(context.Context, ...client.ClientOption) (client.ClientStreamForClient[User, UploadUsersResponse], error)
	Chat(context.Context, ...client.ClientOption) (client.BidiStreamForClient[ChatMessage, ChatMessage], error)

	// Close releases any resources held by the client.
	Close() error
}

type usersServiceHTTPClient struct {
	client.ClientBase
}

// NewUsersServiceHTTPClient creates a new UsersServiceHTTPClient that calls the given base URL.
func NewUsersServiceHTTPClient(baseURL string, opts ...client.ClientOption) UsersServiceHTTPClient {
	return &usersServiceHTTPClient{ClientBase: client.NewClientBase(baseURL, opts...)}
}

func (c *usersServiceHTTPClient) GetUser(ctx context.Context, req *GetUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodGet, UsersService_GetUser_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) ListUsers(ctx context.Context, req *ListUsersRequest, extraOpts ...client.ClientOption) (*ListUsersResponse, error) {
	resp := &ListUsersResponse{}
	err := c.DoUnary(ctx, http.MethodGet, UsersService_ListUsers_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) GetUserByID(ctx context.Context, req *GetUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodGet, UsersService_GetUserByID_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) CreateUser(ctx context.Context, req *CreateUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodPost, UsersService_CreateUser_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) UpdateUser(ctx context.Context, req *UpdateUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodPut, UsersService_UpdateUser_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) DeleteUser(ctx context.Context, req *DeleteUserRequest, extraOpts ...client.ClientOption) (*emptypb.Empty, error) {
	resp := &emptypb.Empty{}
	err := c.DoUnary(ctx, http.MethodDelete, UsersService_DeleteUser_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) Echo(ctx context.Context, req *EchoRequest, extraOpts ...client.ClientOption) (*EchoResponse, error) {
	resp := &EchoResponse{}
	err := c.DoUnary(ctx, http.MethodPost, UsersService_Echo_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) GetUserProfile(ctx context.Context, req *GetUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodGet, UsersService_GetUserProfile_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) ActivateUser(ctx context.Context, req *ActivateUserRequest, extraOpts ...client.ClientOption) (*User, error) {
	resp := &User{}
	err := c.DoUnary(ctx, http.MethodPost, UsersService_ActivateUser_Path, "", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *usersServiceHTTPClient) WatchUsers(ctx context.Context, req *WatchUsersRequest, extraOpts ...client.ClientOption) (client.ServerStreamForClient[User], error) {
	raw, err := c.DoServerStream(ctx, http.MethodGet, UsersService_WatchUsers_Path, req, reflect.TypeOf((*User)(nil)).Elem(), extraOpts...)
	if err != nil {
		return client.ServerStreamForClient[User]{}, err
	}
	return client.ServerStreamForClient[User]{Inner: raw}, nil
}

func (c *usersServiceHTTPClient) UploadUsers(ctx context.Context, extraOpts ...client.ClientOption) (client.ClientStreamForClient[User, UploadUsersResponse], error) {
	raw, err := c.DoClientStream(ctx, http.MethodPost, UsersService_UploadUsers_Path, reflect.TypeOf((*UploadUsersResponse)(nil)).Elem(), extraOpts...)
	if err != nil {
		return client.ClientStreamForClient[User, UploadUsersResponse]{}, err
	}
	return client.ClientStreamForClient[User, UploadUsersResponse]{Inner: raw}, nil
}

func (c *usersServiceHTTPClient) Chat(ctx context.Context, extraOpts ...client.ClientOption) (client.BidiStreamForClient[ChatMessage, ChatMessage], error) {
	raw, err := c.DoBidiStream(ctx, UsersService_Chat_Path, reflect.TypeOf((*ChatMessage)(nil)).Elem(), extraOpts...)
	if err != nil {
		return client.BidiStreamForClient[ChatMessage, ChatMessage]{}, err
	}
	return client.BidiStreamForClient[ChatMessage, ChatMessage]{Inner: raw}, nil
}

func (c *usersServiceHTTPClient) Close() error {
	return nil
}

// AuthServiceHandler is the server implementation contract.
type AuthServiceHandler interface {
	Register(runtime.Ctx, *RegisterRequest) (*RegisterResponse, error)
	Login(runtime.Ctx, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedAuthServiceHandler returns CodeUnimplemented for every method.
type UnimplementedAuthServiceHandler struct{}

func (UnimplementedAuthServiceHandler) Register(runtime.Ctx, *RegisterRequest) (*RegisterResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method Register not implemented")
}

func (UnimplementedAuthServiceHandler) Login(runtime.Ctx, *LoginRequest) (*LoginResponse, error) {
	return nil, status.NewErrorf(codes.CodeUnimplemented, "method Login not implemented")
}

func request_AuthService_Register_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &RegisterRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

func request_AuthService_Login_0(ctx runtime.Ctx, r *http.Request, params map[string]string, spec runtime.Spec, codec encoding.Codec) (runtime.AnyRequest, error) {
	msg := &LoginRequest{}
	meta := ctx.Meta()

	// Body: entire request message (buffered by the mux).
	if err := codec.Unmarshal(meta.Body, msg); err != nil {
		return nil, status.NewErrorf(codes.CodeInvalidArgument, "decode request body: %v", err)
	}

	return runtime.NewRequestWithMeta(msg, meta.Header, spec, peer.Peer{Addr: r.RemoteAddr, Protocol: r.Proto}), nil
}

// Service and endpoint constants.
const (
	AuthService_FullName        = "acme.users.v1.AuthService"
	AuthService_Register_Method = "Register"
	AuthService_Register_Path   = "/v1/auth/register"
	AuthService_Login_Method    = "Login"
	AuthService_Login_Path      = "/v1/auth/login"
)

// Register_Register builds the Register endpoint.
func Register_Register(svc AuthServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[RegisterRequest, RegisterResponse])(&op).
		SetMethod(http.MethodPost).
		SetPath(AuthService_Register_Path).
		SetRPC(AuthService_Register_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[RegisterRequest]) (*runtime.Response[RegisterResponse], error) {
			resp, err := svc.Register(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_AuthService_Register_0).
		Build()
}

// Register_Login builds the Login endpoint.
func Register_Login(svc AuthServiceHandler) *kernel.Operation {
	var op kernel.Operation
	return (*kernel.OperationBuilder[LoginRequest, LoginResponse])(&op).
		SetMethod(http.MethodPost).
		SetPath(AuthService_Login_Path).
		SetRPC(AuthService_Login_Method).
		SetUnaryHandler(func(ctx runtime.Ctx, req *runtime.Request[LoginRequest]) (*runtime.Response[LoginResponse], error) {
			resp, err := svc.Login(ctx, req.Msg())
			if err != nil {
				return nil, err
			}
			return runtime.NewResponse(resp), nil
		}).
		SetBody("*").
		SetRequestBuilder(request_AuthService_Login_0).
		Build()
}

// RegisterAuthServiceRoutes registers all HTTP endpoints of the service on the mux.
func RegisterAuthServiceRoutes(mux *routing.Mux, svc AuthServiceHandler) error {
	return mux.Register(
		kernel.NewService(
			AuthService_FullName,
			Register_Register(svc),
			Register_Login(svc),
		))
}

// RegisterAuthServiceHandler registers the service on target (routing.Server, routing.Mux, or gRPC registrar).
func RegisterAuthServiceHandler(target any, svc AuthServiceHandler) error {
	if reg, ok := target.(interface {
		Mux() *routing.Mux
		GRPC() any
	}); ok {
		if err := RegisterAuthServiceRoutes(reg.Mux(), svc); err != nil {
			return err
		}
		if g := reg.GRPC(); g != nil {
			RegisterAuthServiceServer(g, svc)
		}
		return nil
	}
	if mux, ok := target.(*routing.Mux); ok {
		return RegisterAuthServiceRoutes(mux, svc)
	}
	RegisterAuthServiceServer(target, svc)
	return nil
}

// AuthServiceHTTPClient is a typed HTTP client for AuthService.
type AuthServiceHTTPClient interface {
	Register(context.Context, *RegisterRequest, ...client.ClientOption) (*RegisterResponse, error)
	Login(context.Context, *LoginRequest, ...client.ClientOption) (*LoginResponse, error)

	// Close releases any resources held by the client.
	Close() error
}

type authServiceHTTPClient struct {
	client.ClientBase
}

// NewAuthServiceHTTPClient creates a new AuthServiceHTTPClient that calls the given base URL.
func NewAuthServiceHTTPClient(baseURL string, opts ...client.ClientOption) AuthServiceHTTPClient {
	return &authServiceHTTPClient{ClientBase: client.NewClientBase(baseURL, opts...)}
}

func (c *authServiceHTTPClient) Register(ctx context.Context, req *RegisterRequest, extraOpts ...client.ClientOption) (*RegisterResponse, error) {
	resp := &RegisterResponse{}
	err := c.DoUnary(ctx, http.MethodPost, AuthService_Register_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *authServiceHTTPClient) Login(ctx context.Context, req *LoginRequest, extraOpts ...client.ClientOption) (*LoginResponse, error) {
	resp := &LoginResponse{}
	err := c.DoUnary(ctx, http.MethodPost, AuthService_Login_Path, "*", req, resp, extraOpts...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *authServiceHTTPClient) Close() error {
	return nil
}
