// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: users/v1/users.proto

package usersv1

import (
	metadata "github.com/aldok10/zara-rpc/metadata"
	runtime "github.com/aldok10/zara-rpc/runtime"
	status "github.com/aldok10/zara-rpc/status"
	grpc "google.golang.org/grpc"
	metadata1 "google.golang.org/grpc/metadata"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	io "io"
)

// gatewayUsersService adapts the grpc-go client to the zararpc HTTP handler
// contract. It is used by RegisterUsersServiceGateway.
type gatewayUsersService struct {
	UnimplementedUsersServiceHandler
	client UsersServiceClient
}

func (g *gatewayUsersService) GetUser(ctx runtime.Ctx, req *GetUserRequest) (*User, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.GetUser(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) ListUsers(ctx runtime.Ctx, req *ListUsersRequest) (*ListUsersResponse, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.ListUsers(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) CreateUser(ctx runtime.Ctx, req *CreateUserRequest) (*User, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.CreateUser(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) UpdateUser(ctx runtime.Ctx, req *UpdateUserRequest) (*User, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.UpdateUser(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) DeleteUser(ctx runtime.Ctx, req *DeleteUserRequest) (*emptypb.Empty, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.DeleteUser(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) Echo(ctx runtime.Ctx, req *EchoRequest) (*EchoResponse, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	resp, err := g.client.Echo(gctx, req)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) WatchUsers(ctx runtime.Ctx, req *WatchUsersRequest, stream runtime.ServerStream[*User]) error {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	clientStream, err := g.client.WatchUsers(gctx, req)
	if err != nil {
		return status.FromGRPCStatus(err)
	}
	for {
		msg, err := clientStream.Recv()
		if err == io.EOF {
			return nil
		}
		if err != nil {
			return status.FromGRPCStatus(err)
		}
		if err := stream.Send(msg); err != nil {
			return err
		}
	}
}

func (g *gatewayUsersService) UploadUsers(ctx runtime.Ctx, stream runtime.ClientStream[*User]) (*UploadUsersResponse, error) {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	clientStream, err := g.client.UploadUsers(gctx)
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	for {
		msg, err := stream.Receive()
		if err == io.EOF {
			break
		}
		if err != nil {
			return nil, err
		}
		if err := clientStream.Send(msg); err != nil {
			return nil, status.FromGRPCStatus(err)
		}
	}
	resp, err := clientStream.CloseAndRecv()
	if err != nil {
		return nil, status.FromGRPCStatus(err)
	}
	return resp, nil
}

func (g *gatewayUsersService) Chat(ctx runtime.Ctx, stream runtime.BidiStream[*ChatMessage, *ChatMessage]) error {
	gctx := ctx.Context()
	if pairs := metadata.HeaderPairsFromMeta(ctx.Meta()); len(pairs) > 0 {
		gctx = metadata1.AppendToOutgoingContext(gctx, pairs...)
	}
	clientStream, err := g.client.Chat(gctx)
	if err != nil {
		return status.FromGRPCStatus(err)
	}
	errCh := make(chan error, 2)
	go func() {
		for {
			msg, err := stream.Receive()
			if err == io.EOF {
				clientStream.CloseSend()
				errCh <- nil
				return
			}
			if err != nil {
				errCh <- err
				return
			}
			if err := clientStream.Send(msg); err != nil {
				errCh <- status.FromGRPCStatus(err)
				return
			}
		}
	}()
	go func() {
		for {
			msg, err := clientStream.Recv()
			if err == io.EOF {
				errCh <- nil
				return
			}
			if err != nil {
				errCh <- status.FromGRPCStatus(err)
				return
			}
			if err := stream.Send(msg); err != nil {
				errCh <- err
				return
			}
		}
	}()
	var firstErr error
	for i := 0; i < 2; i++ {
		if err := <-errCh; err != nil && firstErr == nil {
			firstErr = err
		}
	}
	return firstErr
}

// RegisterUsersServiceGateway registers REST routes on mux that proxy
// every call to the gRPC server reachable through conn.
func RegisterUsersServiceGateway(mux *runtime.Mux, conn *grpc.ClientConn) error {
	svc := &gatewayUsersService{client: NewUsersServiceClient(conn)}
	return RegisterUsersServiceRoutes(mux, svc)
}
