// Code generated by protoc-gen-zararpc. DO NOT EDIT.
// versions:
// - protoc-gen-zararpc v0.1.0
// - protoc (unknown)
// source: users/v1/users.proto

package usersv1

import (
	context "context"
	grpcbridge "github.com/aldok10/zara-rpc/grpcbridge"
	grpc "google.golang.org/grpc"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// FullMethodName constants for the service.
const (
	UsersService_GetUser_FullMethodName        = "/acme.users.v1.UsersService/GetUser"
	UsersService_ListUsers_FullMethodName      = "/acme.users.v1.UsersService/ListUsers"
	UsersService_GetUserByID_FullMethodName    = "/acme.users.v1.UsersService/GetUserByID"
	UsersService_CreateUser_FullMethodName     = "/acme.users.v1.UsersService/CreateUser"
	UsersService_UpdateUser_FullMethodName     = "/acme.users.v1.UsersService/UpdateUser"
	UsersService_DeleteUser_FullMethodName     = "/acme.users.v1.UsersService/DeleteUser"
	UsersService_Echo_FullMethodName           = "/acme.users.v1.UsersService/Echo"
	UsersService_GetUserProfile_FullMethodName = "/acme.users.v1.UsersService/GetUserProfile"
	UsersService_ActivateUser_FullMethodName   = "/acme.users.v1.UsersService/ActivateUser"
	UsersService_WatchUsers_FullMethodName     = "/acme.users.v1.UsersService/WatchUsers"
	UsersService_UploadUsers_FullMethodName    = "/acme.users.v1.UsersService/UploadUsers"
	UsersService_Chat_FullMethodName           = "/acme.users.v1.UsersService/Chat"
)

// UsersServiceClient is the client API for UsersService.
type UsersServiceClient interface {
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUserByID(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	GetUserProfile(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*User, error)
	WatchUsers(ctx context.Context, in *WatchUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[User], error)
	UploadUsers(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[User, UploadUsersResponse], error)
	Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error)
}

type usersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersServiceClient(cc grpc.ClientConnInterface) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_GetUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, UsersService_ListUsers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserByID(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_GetUserByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_CreateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_UpdateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, UsersService_DeleteUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, UsersService_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) GetUserProfile(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_GetUserProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) ActivateUser(ctx context.Context, in *ActivateUserRequest, opts ...grpc.CallOption) (*User, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(User)
	err := c.cc.Invoke(ctx, UsersService_ActivateUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersServiceClient) WatchUsers(ctx context.Context, in *WatchUsersRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[User], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UsersService_ServiceDesc.Streams[0], UsersService_WatchUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchUsersRequest, User]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

func (c *usersServiceClient) UploadUsers(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[User, UploadUsersResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UsersService_ServiceDesc.Streams[1], UsersService_UploadUsers_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[User, UploadUsersResponse]{ClientStream: stream}
	return x, nil
}

func (c *usersServiceClient) Chat(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ChatMessage, ChatMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &UsersService_ServiceDesc.Streams[2], UsersService_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatMessage, ChatMessage]{ClientStream: stream}
	return x, nil
}

// UsersService_ServiceDesc is the grpc.ServiceDesc for UsersService.
var UsersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.users.v1.UsersService",
	HandlerType: (*UsersServiceHandler)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "GetUser", Handler: _UsersService_GetUser_Handler},
		{MethodName: "ListUsers", Handler: _UsersService_ListUsers_Handler},
		{MethodName: "GetUserByID", Handler: _UsersService_GetUserByID_Handler},
		{MethodName: "CreateUser", Handler: _UsersService_CreateUser_Handler},
		{MethodName: "UpdateUser", Handler: _UsersService_UpdateUser_Handler},
		{MethodName: "DeleteUser", Handler: _UsersService_DeleteUser_Handler},
		{MethodName: "Echo", Handler: _UsersService_Echo_Handler},
		{MethodName: "GetUserProfile", Handler: _UsersService_GetUserProfile_Handler},
		{MethodName: "ActivateUser", Handler: _UsersService_ActivateUser_Handler},
	},
	Streams: []grpc.StreamDesc{
		{StreamName: "WatchUsers", Handler: _UsersService_WatchUsers_Handler, ServerStreams: true},
		{StreamName: "UploadUsers", Handler: _UsersService_UploadUsers_Handler, ClientStreams: true},
		{StreamName: "Chat", Handler: _UsersService_Chat_Handler, ServerStreams: true, ClientStreams: true},
	},
	Metadata: "users/v1/users.proto",
}

func _UsersService_GetUser_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).GetUser(grpcbridge.CtxFor(ctx, UsersService_GetUser_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_GetUser_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).GetUser(grpcbridge.CtxFor(ctx, UsersService_GetUser_FullMethodName), req.(*GetUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_ListUsers_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).ListUsers(grpcbridge.CtxFor(ctx, UsersService_ListUsers_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_ListUsers_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).ListUsers(grpcbridge.CtxFor(ctx, UsersService_ListUsers_FullMethodName), req.(*ListUsersRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserByID_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).GetUserByID(grpcbridge.CtxFor(ctx, UsersService_GetUserByID_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_GetUserByID_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).GetUserByID(grpcbridge.CtxFor(ctx, UsersService_GetUserByID_FullMethodName), req.(*GetUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_CreateUser_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).CreateUser(grpcbridge.CtxFor(ctx, UsersService_CreateUser_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_CreateUser_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).CreateUser(grpcbridge.CtxFor(ctx, UsersService_CreateUser_FullMethodName), req.(*CreateUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_UpdateUser_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).UpdateUser(grpcbridge.CtxFor(ctx, UsersService_UpdateUser_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_UpdateUser_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).UpdateUser(grpcbridge.CtxFor(ctx, UsersService_UpdateUser_FullMethodName), req.(*UpdateUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_DeleteUser_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).DeleteUser(grpcbridge.CtxFor(ctx, UsersService_DeleteUser_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_DeleteUser_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).DeleteUser(grpcbridge.CtxFor(ctx, UsersService_DeleteUser_FullMethodName), req.(*DeleteUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_Echo_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).Echo(grpcbridge.CtxFor(ctx, UsersService_Echo_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_Echo_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).Echo(grpcbridge.CtxFor(ctx, UsersService_Echo_FullMethodName), req.(*EchoRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_GetUserProfile_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).GetUserProfile(grpcbridge.CtxFor(ctx, UsersService_GetUserProfile_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_GetUserProfile_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).GetUserProfile(grpcbridge.CtxFor(ctx, UsersService_GetUserProfile_FullMethodName), req.(*GetUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_ActivateUser_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(ActivateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(UsersServiceHandler).ActivateUser(grpcbridge.CtxFor(ctx, UsersService_ActivateUser_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: UsersService_ActivateUser_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(UsersServiceHandler).ActivateUser(grpcbridge.CtxFor(ctx, UsersService_ActivateUser_FullMethodName), req.(*ActivateUserRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersService_WatchUsers_Handler(srv any, stream grpc.ServerStream) error {
	m := new(WatchUsersRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	if err := srv.(UsersServiceHandler).WatchUsers(grpcbridge.CtxFor(stream.Context(), UsersService_WatchUsers_FullMethodName), m, &grpcbridge.ServerStreamAdapter[User]{Stream: stream}); err != nil {
		return grpcbridge.ToGRPC(err)
	}
	return nil
}

func _UsersService_UploadUsers_Handler(srv any, stream grpc.ServerStream) error {
	resp, err := srv.(UsersServiceHandler).UploadUsers(grpcbridge.CtxFor(stream.Context(), UsersService_UploadUsers_FullMethodName), &grpcbridge.ClientStreamAdapter[User]{Stream: stream})
	if err != nil {
		return grpcbridge.ToGRPC(err)
	}
	return stream.SendMsg(resp)
}

func _UsersService_Chat_Handler(srv any, stream grpc.ServerStream) error {
	if err := srv.(UsersServiceHandler).Chat(grpcbridge.CtxFor(stream.Context(), UsersService_Chat_FullMethodName), &grpcbridge.BidiStreamAdapter[ChatMessage, ChatMessage]{Stream: stream}); err != nil {
		return grpcbridge.ToGRPC(err)
	}
	return nil
}

// RegisterUsersServiceServer registers the service on a grpc.ServiceRegistrar or any target implementing RegisterService.
// Handlers receive runtime.Ctx (the same contract as the HTTP routes),
// so one implementation serves both transports.
func RegisterUsersServiceServer(s any, svc UsersServiceHandler) {
	if reg, ok := s.(grpc.ServiceRegistrar); ok {
		reg.RegisterService(&UsersService_ServiceDesc, svc)
	}
}

// FullMethodName constants for the service.
const (
	AuthService_Register_FullMethodName = "/acme.users.v1.AuthService/Register"
	AuthService_Login_FullMethodName    = "/acme.users.v1.AuthService/Login"
)

// AuthServiceClient is the client API for AuthService.
type AuthServiceClient interface {
	Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type authServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthServiceClient(cc grpc.ClientConnInterface) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Register(ctx context.Context, in *RegisterRequest, opts ...grpc.CallOption) (*RegisterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterResponse)
	err := c.cc.Invoke(ctx, AuthService_Register_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, AuthService_Login_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthService_ServiceDesc is the grpc.ServiceDesc for AuthService.
var AuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "acme.users.v1.AuthService",
	HandlerType: (*AuthServiceHandler)(nil),
	Methods: []grpc.MethodDesc{
		{MethodName: "Register", Handler: _AuthService_Register_Handler},
		{MethodName: "Login", Handler: _AuthService_Login_Handler},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users/v1/users.proto",
}

func _AuthService_Register_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(RegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(AuthServiceHandler).Register(grpcbridge.CtxFor(ctx, AuthService_Register_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: AuthService_Register_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(AuthServiceHandler).Register(grpcbridge.CtxFor(ctx, AuthService_Register_FullMethodName), req.(*RegisterRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_Login_Handler(srv any, ctx context.Context, dec func(any) error, interceptor grpc.UnaryServerInterceptor) (any, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		resp, err := srv.(AuthServiceHandler).Login(grpcbridge.CtxFor(ctx, AuthService_Login_FullMethodName), in)
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	info := &grpc.UnaryServerInfo{Server: srv, FullMethod: AuthService_Login_FullMethodName}
	handler := func(ctx context.Context, req any) (any, error) {
		resp, err := srv.(AuthServiceHandler).Login(grpcbridge.CtxFor(ctx, AuthService_Login_FullMethodName), req.(*LoginRequest))
		if err != nil {
			return nil, grpcbridge.ToGRPC(err)
		}
		return resp, nil
	}
	return interceptor(ctx, in, info, handler)
}

// RegisterAuthServiceServer registers the service on a grpc.ServiceRegistrar or any target implementing RegisterService.
// Handlers receive runtime.Ctx (the same contract as the HTTP routes),
// so one implementation serves both transports.
func RegisterAuthServiceServer(s any, svc AuthServiceHandler) {
	if reg, ok := s.(grpc.ServiceRegistrar); ok {
		reg.RegisterService(&AuthService_ServiceDesc, svc)
	}
}
